variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

bitstream:
  stage: build
  image: vivado2018:2018.3
  script:
    - env
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source build.tcl thinpad_top.xpr

  artifacts:
    paths:
      - thinpad_top.runs/impl_1/thinpad_top.bit
      - thinpad_top.runs/impl_1/runme.log
      - thinpad_top.runs/synth_1/runme.log

