#Clock
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports clk_50M]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports clk_11M0592]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_11M0592_IBUF]

create_clock -period 20.000 -name clk_50M -waveform {0.000 10.000} [get_ports clk_50M]
create_clock -period 90.422 -name clk_11M0592 -waveform {0.000 45.211} [get_ports clk_11M0592]

#Touch Button
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {touch_btn[0]}]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS33} [get_ports {touch_btn[1]}]
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS33} [get_ports {touch_btn[2]}]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS33} [get_ports {touch_btn[3]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33} [get_ports clock_btn]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports reset_btn]

#required if touch button used as manual clock source
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clock_btn_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_btn_IBUF]

#CPLD
set_property -dict {PACKAGE_PIN L8 IOSTANDARD LVCMOS33} [get_ports uart_wrn]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports uart_rdn]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports uart_tbre]
set_property -dict {PACKAGE_PIN L7 IOSTANDARD LVCMOS33} [get_ports uart_tsre]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports uart_dataready]

#Ext serial
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L19} [get_ports txd]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K21} [get_ports rxd]

# USB + SD
set_property -dict {PACKAGE_PIN K7 IOSTANDARD LVCMOS33} [get_ports ch376t_sdo]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports ch376t_sdi]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports ch376t_sck]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports ch376t_cs_n]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports ch376t_rst]
set_property -dict {PACKAGE_PIN R7 IOSTANDARD LVCMOS33} [get_ports ch376t_int_n]

# KSZ8795 Ethernet Switch
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_rd[0]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_rd[1]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_rd[2]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_rd[3]}]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33} [get_ports eth_rgmii_rx_ctl]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports eth_rgmii_rxc]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_td[0]}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_td[1]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_td[2]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {eth_rgmii_td[3]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports eth_rgmii_tx_ctl]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports eth_rgmii_txc]

set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports eth_rst_n]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports eth_int_n]

set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports eth_spi_mosi]
set_property -dict {PACKAGE_PIN K5 IOSTANDARD LVCMOS33} [get_ports eth_spi_miso]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports eth_spi_sck]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports eth_spi_ss_n]

#Digital Video
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports video_clk]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {video_red[2]}]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33} [get_ports {video_red[1]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports {video_red[0]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {video_green[2]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {video_green[1]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {video_green[0]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {video_blue[1]}]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {video_blue[0]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports video_hsync]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports video_vsync]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports video_de]

#LEDS
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {leds[0]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {leds[1]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {leds[2]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {leds[3]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {leds[4]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {leds[5]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {leds[6]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {leds[7]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {leds[8]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {leds[9]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {leds[10]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {leds[11]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {leds[12]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports {leds[13]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {leds[14]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {leds[15]}]

#DPY0
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {dpy0[0]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports {dpy0[1]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {dpy0[2]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {dpy0[3]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {dpy0[4]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {dpy0[5]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {dpy0[6]}]
set_property -dict {PACKAGE_PIN J8 IOSTANDARD LVCMOS33} [get_ports {dpy0[7]}]

#DPY1
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} [get_ports {dpy1[0]}]
set_property -dict {PACKAGE_PIN G8 IOSTANDARD LVCMOS33} [get_ports {dpy1[1]}]
set_property -dict {PACKAGE_PIN G7 IOSTANDARD LVCMOS33} [get_ports {dpy1[2]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {dpy1[3]}]
set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS33} [get_ports {dpy1[4]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports {dpy1[5]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {dpy1[6]}]
set_property -dict {PACKAGE_PIN G5 IOSTANDARD LVCMOS33} [get_ports {dpy1[7]}]

#DIP_SW
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports {dip_sw[0]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports {dip_sw[1]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {dip_sw[2]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {dip_sw[3]}]
set_property -dict {PACKAGE_PIN R5 IOSTANDARD LVCMOS33} [get_ports {dip_sw[4]}]
set_property -dict {PACKAGE_PIN T7 IOSTANDARD LVCMOS33} [get_ports {dip_sw[5]}]
set_property -dict {PACKAGE_PIN R8 IOSTANDARD LVCMOS33} [get_ports {dip_sw[6]}]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS33} [get_ports {dip_sw[7]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports {dip_sw[8]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports {dip_sw[9]}]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports {dip_sw[10]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {dip_sw[11]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports {dip_sw[12]}]
set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVCMOS33} [get_ports {dip_sw[13]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports {dip_sw[14]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {dip_sw[15]}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS33} [get_ports {dip_sw[16]}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports {dip_sw[17]}]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports {dip_sw[18]}]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports {dip_sw[19]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS33} [get_ports {dip_sw[20]}]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS33} [get_ports {dip_sw[21]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {dip_sw[22]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {dip_sw[23]}]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports {dip_sw[24]}]
set_property -dict {PACKAGE_PIN P6 IOSTANDARD LVCMOS33} [get_ports {dip_sw[25]}]
set_property -dict {PACKAGE_PIN P8 IOSTANDARD LVCMOS33} [get_ports {dip_sw[26]}]
set_property -dict {PACKAGE_PIN N8 IOSTANDARD LVCMOS33} [get_ports {dip_sw[27]}]
set_property -dict {PACKAGE_PIN N6 IOSTANDARD LVCMOS33} [get_ports {dip_sw[28]}]
set_property -dict {PACKAGE_PIN N7 IOSTANDARD LVCMOS33} [get_ports {dip_sw[29]}]
set_property -dict {PACKAGE_PIN M7 IOSTANDARD LVCMOS33} [get_ports {dip_sw[30]}]
set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVCMOS33} [get_ports {dip_sw[31]}]

set_property -dict {PACKAGE_PIN K8 IOSTANDARD LVCMOS33} [get_ports {flash_a[0]}]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33} [get_ports {flash_a[1]}]
set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVCMOS33} [get_ports {flash_a[2]}]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS33} [get_ports {flash_a[3]}]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD LVCMOS33} [get_ports {flash_a[4]}]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS33} [get_ports {flash_a[5]}]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33} [get_ports {flash_a[6]}]
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS33} [get_ports {flash_a[7]}]
set_property -dict {PACKAGE_PIN A24 IOSTANDARD LVCMOS33} [get_ports {flash_a[8]}]
set_property -dict {PACKAGE_PIN C23 IOSTANDARD LVCMOS33} [get_ports {flash_a[9]}]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS33} [get_ports {flash_a[10]}]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS33} [get_ports {flash_a[11]}]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33} [get_ports {flash_a[12]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports {flash_a[13]}]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports {flash_a[14]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports {flash_a[15]}]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS33} [get_ports {flash_a[16]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {flash_a[17]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {flash_a[18]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {flash_a[19]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {flash_a[20]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports {flash_a[21]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {flash_a[22]}]

set_property -dict {PACKAGE_PIN F8 IOSTANDARD LVCMOS33} [get_ports {flash_d[0]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {flash_d[1]}]
set_property -dict {PACKAGE_PIN B5 IOSTANDARD LVCMOS33} [get_ports {flash_d[2]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {flash_d[3]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {flash_d[4]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {flash_d[5]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {flash_d[6]}]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports {flash_d[7]}]
set_property -dict {PACKAGE_PIN F7 IOSTANDARD LVCMOS33} [get_ports {flash_d[8]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {flash_d[9]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {flash_d[10]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {flash_d[11]}]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS33} [get_ports {flash_d[12]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {flash_d[13]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {flash_d[14]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {flash_d[15]}]

set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVCMOS33} [get_ports flash_byte_n]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS33} [get_ports flash_ce_n]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports flash_oe_n]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports flash_rp_n]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports flash_vpen]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports flash_we_n]

set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[0]}]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[1]}]
set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[2]}]
set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[3]}]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[4]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[5]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[6]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[7]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[8]}]
set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[9]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[10]}]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[11]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[12]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[13]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[14]}]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[15]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[16]}]
set_property -dict {PACKAGE_PIN N23 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[17]}]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[18]}]
set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS33} [get_ports {base_ram_addr[19]}]
set_property -dict {PACKAGE_PIN M26 IOSTANDARD LVCMOS33} [get_ports {base_ram_be_n[0]}]
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS33} [get_ports {base_ram_be_n[1]}]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS33} [get_ports {base_ram_be_n[2]}]
set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVCMOS33} [get_ports {base_ram_be_n[3]}]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[0]}]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[1]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[2]}]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[3]}]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[4]}]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[5]}]
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[6]}]
set_property -dict {PACKAGE_PIN P25 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[7]}]
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[8]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[9]}]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[10]}]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[11]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[12]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[13]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[14]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[15]}]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[16]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[17]}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[18]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[19]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[20]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[21]}]
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[22]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[23]}]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[24]}]
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[25]}]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[26]}]
set_property -dict {PACKAGE_PIN J25 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[27]}]
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[28]}]
set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[29]}]
set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[30]}]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS33} [get_ports {base_ram_data[31]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports base_ram_ce_n]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports base_ram_oe_n]
set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS33} [get_ports base_ram_we_n]

set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[0]}]
set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[1]}]
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[2]}]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[3]}]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[5]}]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[6]}]
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[7]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[8]}]
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[9]}]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[10]}]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[11]}]
set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[12]}]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[13]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[14]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[15]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[16]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[17]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[18]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {ext_ram_addr[19]}]
set_property -dict {PACKAGE_PIN U26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_be_n[0]}]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_be_n[1]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {ext_ram_be_n[2]}]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports {ext_ram_be_n[3]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[0]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[1]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[2]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[3]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[4]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[5]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[6]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[7]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[8]}]
set_property -dict {PACKAGE_PIN W25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[9]}]
set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[10]}]
set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[11]}]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[12]}]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[13]}]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[14]}]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[15]}]
set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[16]}]
set_property -dict {PACKAGE_PIN AC26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[17]}]
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[18]}]
set_property -dict {PACKAGE_PIN AB24 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[19]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[20]}]
set_property -dict {PACKAGE_PIN AA24 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[21]}]
set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[22]}]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[23]}]
set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[24]}]
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[25]}]
set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[26]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[27]}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[28]}]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[29]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[30]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {ext_ram_data[31]}]
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33} [get_ports ext_ram_ce_n]
set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33} [get_ports ext_ram_oe_n]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports ext_ram_we_n]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]


set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[5]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[6]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[11]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[13]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[18]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[20]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[21]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[9]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[0]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[2]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[3]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[12]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[15]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[22]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[24]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[25]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[26]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[31]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[30]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[29]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[1]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[7]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[14]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[16]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[19]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[23]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[4]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[8]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[10]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[17]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[27]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_ed[28]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_st[0]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_st[1]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/buffer_st[2]}]


set_property MARK_DEBUG true [get_nets rx_crc_filter/eth_rx_axis_fifo_tlast]
set_property MARK_DEBUG true [get_nets rx_crc_filter/eth_rx_axis_fifo_tvalid]
set_property MARK_DEBUG true [get_nets rx_crc_filter/eth_rx_axis_no_crc_tlast]
set_property MARK_DEBUG true [get_nets rx_crc_filter/eth_rx_axis_no_crc_tvalid]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[0]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[1]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[2]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[3]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[4]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[5]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[6]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/tx_axis_mac_tdata[7]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[0]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[1]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[2]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[3]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[4]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[5]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[6]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/rx_axis_mac_tdata[7]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[12]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[13]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[8]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[10]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[7]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[11]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[9]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[14]}]
set_property MARK_DEBUG true [get_nets {rx_crc_filter/leds_OBUF[15]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[3]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[4]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[5]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[6]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/dob[7]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/E[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_0_in[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_0_in[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_0_in[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_0_in[3]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_0_in[4]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_0_in[5]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_1_in[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_1_in[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_1_in[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_1_in[3]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_1_in[4]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/p_1_in[5]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[3]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[4]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[5]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[6]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/Q[7]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/SR[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_state_reg[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_state_reg[1]}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/CLK]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_2__0_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_4_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_5_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_2__0_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_4__0_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_5_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state_reg[1]_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rd_count_12]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rd_slot0]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[2]_i_1__0_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/p_16_out]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/tx_axis_fifo_tdata[7]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_addr[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/wr_eof_reg]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[2]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[2]_i_5_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[2]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rd_count_12_i_1_n_0]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[1]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_addr[2]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_slot[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/wr_slot1]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_slot[2]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/packet_waiting]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rd_count_12_reg_n_0]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[2]_i_4_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rx_axis_tlast_int]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_slot[0]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/packet_waiting018_out]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/p_23_out]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[2]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[2]_i_4_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rx_axis_fifo_tvalid_reg]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[2]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[0]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count[3]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rd_count_6]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot_reg[0]_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/tx_axis_fifo_tlast_int_reg_0]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/tx_axis_fifo_tvalid_i_1_n_0]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_addr[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/gtx_resetn]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/new_packet_start_i_1_n_0]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[1]_i_1__0_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rx_axis_fifo_tlast_reg]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count[3]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_slot[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/ram_loop[0].RAM64X1D_inst_i_1_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/packet_waiting_i_1_n_0]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_addr[0]_i_1__1_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rd_count_6_i_1_n_0]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/rx_axis_tvalid_int]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_addr[2]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/new_packet_start]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[1]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_addr[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/tx_axis_fifo_tvalid_reg_0]
set_property MARK_DEBUG true [get_nets temac_pat_gen/address_swap_inst/tx_axis_fifo_tvalid_reg_1]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_count_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_slot[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_slot[2]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/wr_addr_reg[0]_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[2]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_count[3]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_slot[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {temac_pat_gen/address_swap_inst/rd_state[2]_i_5_n_0}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[0]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[1]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[2]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[3]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[4]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[5]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[6]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/rx_axis_tdata_int[7]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[0]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[1]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[2]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[3]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[4]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[5]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[6]}]
set_property MARK_DEBUG false [get_nets {temac_pat_gen/address_swap_inst/rx_axis_tdata_int[7]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[1]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[11]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[13]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[16]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[21]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[24]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[25]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[30]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[2]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[12]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[14]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[31]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[10]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[3]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[6]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[9]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[17]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[18]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[20]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[27]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[28]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[0]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[4]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[5]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[7]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[8]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[15]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[19]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[22]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[23]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[29]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/p_1_in[26]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[4]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[5]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[6]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[7]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[9]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[17]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[21]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[25]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[2]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[1]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[10]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[11]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[12]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[16]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[22]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[26]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[30]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[3]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[15]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[18]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[19]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[20]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[27]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[31]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[8]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[13]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[14]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[23]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[24]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[28]}]
set_property MARK_DEBUG false [get_nets {rx_crc_filter/data0[29]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[0]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[1]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[2]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[3]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[4]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[5]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[6]}]
set_property MARK_DEBUG true [get_nets {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[7]}]
set_property MARK_DEBUG false [get_nets {trimac_fifo_block/user_side_FIFO/tx_axis_fifo_tdata_reg[7]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {temac_pat_gen/address_swap_inst/dob[0]} {temac_pat_gen/address_swap_inst/dob[1]} {temac_pat_gen/address_swap_inst/dob[2]} {temac_pat_gen/address_swap_inst/dob[3]} {temac_pat_gen/address_swap_inst/dob[4]} {temac_pat_gen/address_swap_inst/dob[5]} {temac_pat_gen/address_swap_inst/dob[6]} {temac_pat_gen/address_swap_inst/dob[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {rx_crc_filter/leds_OBUF[0]} {rx_crc_filter/leds_OBUF[1]} {rx_crc_filter/leds_OBUF[2]} {rx_crc_filter/leds_OBUF[3]} {rx_crc_filter/leds_OBUF[4]} {rx_crc_filter/leds_OBUF[5]} {rx_crc_filter/leds_OBUF[6]} {rx_crc_filter/leds_OBUF[7]} {rx_crc_filter/leds_OBUF[8]} {rx_crc_filter/leds_OBUF[9]} {rx_crc_filter/leds_OBUF[10]} {rx_crc_filter/leds_OBUF[11]} {rx_crc_filter/leds_OBUF[12]} {rx_crc_filter/leds_OBUF[13]} {rx_crc_filter/leds_OBUF[14]} {rx_crc_filter/leds_OBUF[15]}]]
connect_debug_port u_ila_0/probe41 [get_nets [list rx_crc_filter/eth_rx_axis_fifo_tlast]]
connect_debug_port u_ila_0/probe42 [get_nets [list rx_crc_filter/eth_rx_axis_fifo_tvalid]]
connect_debug_port u_ila_0/probe43 [get_nets [list rx_crc_filter/eth_rx_axis_no_crc_tlast]]
connect_debug_port u_ila_0/probe44 [get_nets [list rx_crc_filter/eth_rx_axis_no_crc_tvalid]]
connect_debug_port u_ila_0/probe46 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_2__0_n_0}]]
connect_debug_port u_ila_0/probe47 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_3_n_0}]]
connect_debug_port u_ila_0/probe48 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_4_n_0}]]
connect_debug_port u_ila_0/probe49 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[0]_i_5_n_0}]]
connect_debug_port u_ila_0/probe50 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_1_n_0}]]
connect_debug_port u_ila_0/probe51 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_2__0_n_0}]]
connect_debug_port u_ila_0/probe52 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_4__0_n_0}]]
connect_debug_port u_ila_0/probe58 [get_nets [list temac_pat_gen/address_swap_inst/p_16_out]]
connect_debug_port u_ila_0/probe59 [get_nets [list temac_pat_gen/address_swap_inst/p_23_out]]
connect_debug_port u_ila_0/probe61 [get_nets [list temac_pat_gen/address_swap_inst/packet_waiting018_out]]
connect_debug_port u_ila_0/probe64 [get_nets [list {temac_pat_gen/address_swap_inst/rd_addr[0]_i_1__1_n_0}]]
connect_debug_port u_ila_0/probe65 [get_nets [list {temac_pat_gen/address_swap_inst/rd_addr[1]_i_1__0_n_0}]]
connect_debug_port u_ila_0/probe66 [get_nets [list {temac_pat_gen/address_swap_inst/rd_addr[2]_i_1__0_n_0}]]
connect_debug_port u_ila_0/probe80 [get_nets [list temac_pat_gen/address_swap_inst/rd_count_12_reg_n_0]]
connect_debug_port u_ila_0/probe92 [get_nets [list {temac_pat_gen/address_swap_inst/rd_slot[2]_i_3_n_0}]]
connect_debug_port u_ila_0/probe105 [get_nets [list {temac_pat_gen/address_swap_inst/tx_axis_fifo_tdata[7]_i_3_n_0}]]
connect_debug_port u_ila_0/probe106 [get_nets [list temac_pat_gen/address_swap_inst/tx_axis_fifo_tlast_int_reg_0]]
connect_debug_port u_ila_0/probe108 [get_nets [list temac_pat_gen/address_swap_inst/tx_axis_fifo_tvalid_reg_0]]
connect_debug_port u_ila_0/probe109 [get_nets [list temac_pat_gen/address_swap_inst/tx_axis_fifo_tvalid_reg_1]]
connect_debug_port u_ila_0/probe115 [get_nets [list {temac_pat_gen/address_swap_inst/wr_addr_reg[0]_0}]]
connect_debug_port u_ila_0/probe124 [get_nets [list temac_pat_gen/address_swap_inst/wr_eof_reg]]
connect_debug_port u_ila_0/probe127 [get_nets [list {temac_pat_gen/address_swap_inst/wr_slot[0]_i_2_n_0}]]
connect_debug_port u_ila_0/probe131 [get_nets [list {temac_pat_gen/address_swap_inst/wr_slot[2]_i_3_n_0}]]

connect_debug_port u_ila_0/probe5 [get_nets [list {temac_pat_gen/address_swap_inst/E[0]}]]
connect_debug_port u_ila_0/probe42 [get_nets [list {temac_pat_gen/address_swap_inst/FSM_sequential_wr_state[1]_i_5_n_0}]]
connect_debug_port u_ila_0/probe44 [get_nets [list temac_pat_gen/address_swap_inst/gtx_resetn]]
connect_debug_port u_ila_0/probe56 [get_nets [list {temac_pat_gen/address_swap_inst/ram_loop[0].RAM64X1D_inst_i_1_n_0}]]
connect_debug_port u_ila_0/probe60 [get_nets [list {temac_pat_gen/address_swap_inst/rd_addr[2]_i_5_n_0}]]
connect_debug_port u_ila_0/probe82 [get_nets [list {temac_pat_gen/address_swap_inst/rd_slot_reg[0]_0}]]

connect_debug_port u_ila_0/probe4 [get_nets [list {rx_crc_filter/buffer_st[0]} {rx_crc_filter/buffer_st[1]} {rx_crc_filter/buffer_st[2]}]]

connect_debug_port u_ila_0/clk [get_nets [list clock_gen/inst/clk_out3]]
connect_debug_port u_ila_0/probe0 [get_nets [list {rx_crc_filter/buffer_ed[0]} {rx_crc_filter/buffer_ed[1]} {rx_crc_filter/buffer_ed[2]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {rx_crc_filter/data0[1]} {rx_crc_filter/data0[2]} {rx_crc_filter/data0[3]} {rx_crc_filter/data0[4]} {rx_crc_filter/data0[5]} {rx_crc_filter/data0[6]} {rx_crc_filter/data0[7]} {rx_crc_filter/data0[8]} {rx_crc_filter/data0[9]} {rx_crc_filter/data0[10]} {rx_crc_filter/data0[11]} {rx_crc_filter/data0[12]} {rx_crc_filter/data0[13]} {rx_crc_filter/data0[14]} {rx_crc_filter/data0[15]} {rx_crc_filter/data0[16]} {rx_crc_filter/data0[17]} {rx_crc_filter/data0[18]} {rx_crc_filter/data0[19]} {rx_crc_filter/data0[20]} {rx_crc_filter/data0[21]} {rx_crc_filter/data0[22]} {rx_crc_filter/data0[23]} {rx_crc_filter/data0[24]} {rx_crc_filter/data0[25]} {rx_crc_filter/data0[26]} {rx_crc_filter/data0[27]} {rx_crc_filter/data0[28]} {rx_crc_filter/data0[29]} {rx_crc_filter/data0[30]} {rx_crc_filter/data0[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {rx_crc_filter/no_crc_tdata[0]} {rx_crc_filter/no_crc_tdata[1]} {rx_crc_filter/no_crc_tdata[2]} {rx_crc_filter/no_crc_tdata[3]} {rx_crc_filter/no_crc_tdata[4]} {rx_crc_filter/no_crc_tdata[5]} {rx_crc_filter/no_crc_tdata[6]} {rx_crc_filter/no_crc_tdata[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {rx_crc_filter/fifo_tdata[0]} {rx_crc_filter/fifo_tdata[1]} {rx_crc_filter/fifo_tdata[2]} {rx_crc_filter/fifo_tdata[3]} {rx_crc_filter/fifo_tdata[4]} {rx_crc_filter/fifo_tdata[5]} {rx_crc_filter/fifo_tdata[6]} {rx_crc_filter/fifo_tdata[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {eth_tx_axis_fifo_tdata[0]} {eth_tx_axis_fifo_tdata[1]} {eth_tx_axis_fifo_tdata[2]} {eth_tx_axis_fifo_tdata[3]} {eth_tx_axis_fifo_tdata[4]} {eth_tx_axis_fifo_tdata[5]} {eth_tx_axis_fifo_tdata[6]} {eth_tx_axis_fifo_tdata[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {eth_rx_axis_no_crc_tdata[0]} {eth_rx_axis_no_crc_tdata[1]} {eth_rx_axis_no_crc_tdata[2]} {eth_rx_axis_no_crc_tdata[3]} {eth_rx_axis_no_crc_tdata[4]} {eth_rx_axis_no_crc_tdata[5]} {eth_rx_axis_no_crc_tdata[6]} {eth_rx_axis_no_crc_tdata[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[24]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[25]}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[26]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[27]}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[28]}]]
connect_debug_port u_ila_0/probe32 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[29]}]]
connect_debug_port u_ila_0/probe33 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[30]}]]
connect_debug_port u_ila_0/probe34 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[31]}]]
connect_debug_port u_ila_0/probe35 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe36 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe37 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe38 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe39 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe40 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe41 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe42 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe43 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe44 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe45 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe46 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe47 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe48 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe49 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe50 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe51 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe52 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe53 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe54 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe55 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe56 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[24]}]]
connect_debug_port u_ila_0/probe57 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[25]}]]
connect_debug_port u_ila_0/probe58 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[26]}]]
connect_debug_port u_ila_0/probe59 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[27]}]]
connect_debug_port u_ila_0/probe60 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[28]}]]
connect_debug_port u_ila_0/probe61 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[29]}]]
connect_debug_port u_ila_0/probe62 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[30]}]]
connect_debug_port u_ila_0/probe63 [get_nets [list {rx_crc_filter/buffer_st_reg_n_0_[31]}]]
connect_debug_port dbg_hub/clk [get_nets clk_125M]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

connect_debug_port u_ila_0/probe3 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[3]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[4]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[5]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[6]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[8]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[9]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[10]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[11]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[12]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[13]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[14]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[15]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[16]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[17]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[18]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[19]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[20]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[21]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[22]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[23]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[24]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[25]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[26]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[27]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[28]}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[29]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[30]}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[31]}]]

connect_debug_port u_ila_1/probe3 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[3]}]]
connect_debug_port u_ila_1/probe4 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[4]}]]
connect_debug_port u_ila_1/probe5 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[5]}]]
connect_debug_port u_ila_1/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[6]}]]
connect_debug_port u_ila_1/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[7]}]]
connect_debug_port u_ila_1/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[8]}]]
connect_debug_port u_ila_1/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[9]}]]
connect_debug_port u_ila_1/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[10]}]]
connect_debug_port u_ila_1/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[11]}]]
connect_debug_port u_ila_1/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[12]}]]
connect_debug_port u_ila_1/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[13]}]]
connect_debug_port u_ila_1/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[14]}]]
connect_debug_port u_ila_1/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[15]}]]
connect_debug_port u_ila_1/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[16]}]]
connect_debug_port u_ila_1/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[17]}]]
connect_debug_port u_ila_1/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[18]}]]
connect_debug_port u_ila_1/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[19]}]]
connect_debug_port u_ila_1/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[20]}]]
connect_debug_port u_ila_1/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[21]}]]
connect_debug_port u_ila_1/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[22]}]]
connect_debug_port u_ila_1/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[23]}]]
connect_debug_port u_ila_1/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[24]}]]
connect_debug_port u_ila_1/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[25]}]]
connect_debug_port u_ila_1/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[26]}]]
connect_debug_port u_ila_1/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[27]}]]
connect_debug_port u_ila_1/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[28]}]]
connect_debug_port u_ila_1/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[29]}]]
connect_debug_port u_ila_1/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[30]}]]
connect_debug_port u_ila_1/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[31]}]]
connect_debug_port dbg_hub/clk [get_nets u_ila_2_gtx_clk_out]

connect_debug_port u_ila_0/probe0 [get_nets [list {base_ram_data_IBUF[0]} {base_ram_data_IBUF[1]} {base_ram_data_IBUF[2]} {base_ram_data_IBUF[3]} {base_ram_data_IBUF[4]} {base_ram_data_IBUF[5]} {base_ram_data_IBUF[6]} {base_ram_data_IBUF[7]} {base_ram_data_IBUF[8]} {base_ram_data_IBUF[9]} {base_ram_data_IBUF[10]} {base_ram_data_IBUF[11]} {base_ram_data_IBUF[12]} {base_ram_data_IBUF[13]} {base_ram_data_IBUF[14]} {base_ram_data_IBUF[15]} {base_ram_data_IBUF[16]} {base_ram_data_IBUF[17]} {base_ram_data_IBUF[18]} {base_ram_data_IBUF[19]} {base_ram_data_IBUF[20]} {base_ram_data_IBUF[21]} {base_ram_data_IBUF[22]} {base_ram_data_IBUF[23]} {base_ram_data_IBUF[24]} {base_ram_data_IBUF[25]} {base_ram_data_IBUF[26]} {base_ram_data_IBUF[27]} {base_ram_data_IBUF[28]} {base_ram_data_IBUF[29]} {base_ram_data_IBUF[30]} {base_ram_data_IBUF[31]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/op[0]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/op[1]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/op[2]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/op[3]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/op[4]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/op[5]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func[0]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func[1]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func[2]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func[3]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func[4]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func[5]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func2[0]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func2[1]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func2[2]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func2[3]} {mips_sopc_inst/mips_cpu_inst/inst_decode_inst/func2[4]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[3]}]]
connect_debug_port u_ila_1/probe4 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[4]}]]
connect_debug_port u_ila_1/probe5 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[5]}]]
connect_debug_port u_ila_1/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[6]}]]
connect_debug_port u_ila_1/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[7]}]]
connect_debug_port u_ila_1/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[8]}]]
connect_debug_port u_ila_1/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[9]}]]
connect_debug_port u_ila_1/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[10]}]]
connect_debug_port u_ila_1/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[11]}]]
connect_debug_port u_ila_1/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[12]}]]
connect_debug_port u_ila_1/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[13]}]]
connect_debug_port u_ila_1/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[14]}]]
connect_debug_port u_ila_1/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[15]}]]
connect_debug_port u_ila_1/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[16]}]]
connect_debug_port u_ila_1/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[17]}]]
connect_debug_port u_ila_1/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[18]}]]
connect_debug_port u_ila_1/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[19]}]]
connect_debug_port u_ila_1/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[20]}]]
connect_debug_port u_ila_1/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[21]}]]
connect_debug_port u_ila_1/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[22]}]]
connect_debug_port u_ila_1/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[23]}]]
connect_debug_port u_ila_1/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[24]}]]
connect_debug_port u_ila_1/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[25]}]]
connect_debug_port u_ila_1/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[26]}]]
connect_debug_port u_ila_1/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[27]}]]
connect_debug_port u_ila_1/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[28]}]]
connect_debug_port u_ila_1/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[29]}]]
connect_debug_port u_ila_1/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[30]}]]
connect_debug_port u_ila_1/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_6_[31]}]]

connect_debug_port dbg_hub/clk [get_nets u_ila_3_gtx_clk_out]


connect_debug_port u_ila_0/probe5 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[24]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[25]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[26]}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[27]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[28]}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[29]}]]
connect_debug_port u_ila_0/probe32 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[30]}]]
connect_debug_port u_ila_0/probe33 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_0_[31]}]]

connect_debug_port u_ila_0/probe5 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[3]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[4]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[5]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[6]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[8]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[9]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[10]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[11]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[12]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[13]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[14]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[15]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[16]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[17]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[18]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[19]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[20]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[21]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[22]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[23]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[24]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[25]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[26]}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[27]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[28]}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[29]}]]
connect_debug_port u_ila_0/probe32 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[30]}]]
connect_debug_port u_ila_0/probe33 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_9_[31]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_gen/inst/clk_out3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {lookup_inst/state[0]} {lookup_inst/state[1]} {lookup_inst/state[2]} {lookup_inst/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {rx_crc_filter/buffer_ed[0]} {rx_crc_filter/buffer_ed[1]} {rx_crc_filter/buffer_ed[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {eth_rx_axis_no_crc_tdata[0]} {eth_rx_axis_no_crc_tdata[1]} {eth_rx_axis_no_crc_tdata[2]} {eth_rx_axis_no_crc_tdata[3]} {eth_rx_axis_no_crc_tdata[4]} {eth_rx_axis_no_crc_tdata[5]} {eth_rx_axis_no_crc_tdata[6]} {eth_rx_axis_no_crc_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {eth_tx_axis_fifo_tdata[0]} {eth_tx_axis_fifo_tdata[1]} {eth_tx_axis_fifo_tdata[2]} {eth_tx_axis_fifo_tdata[3]} {eth_tx_axis_fifo_tdata[4]} {eth_tx_axis_fifo_tdata[5]} {eth_tx_axis_fifo_tdata[6]} {eth_tx_axis_fifo_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {eth_rx_axis_fifo_tdata[0]} {eth_rx_axis_fifo_tdata[1]} {eth_rx_axis_fifo_tdata[2]} {eth_rx_axis_fifo_tdata[3]} {eth_rx_axis_fifo_tdata[4]} {eth_rx_axis_fifo_tdata[5]} {eth_rx_axis_fifo_tdata[6]} {eth_rx_axis_fifo_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[18]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[20]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[22]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[24]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[30]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {rx_crc_filter/buffer_ed_reg_n_5_[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list eth_rx_axis_fifo_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list eth_rx_axis_fifo_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list eth_rx_axis_fifo_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list eth_rx_axis_no_crc_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list eth_rx_axis_no_crc_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list eth_rx_axis_no_crc_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list eth_tx_axis_fifo_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list eth_tx_axis_fifo_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list eth_tx_axis_fifo_tvalid]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list trimac_fifo_block/tri_mode_ethernet_mac_i/inst/tri_mode_ethernet_mac_i/rgmii_interface/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[0]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[1]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[2]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[3]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[4]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[5]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[6]} {trimac_fifo_block/user_side_FIFO/rx_axis_mac_tdata[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {trimac_fifo_block/rx_axis_mac_tdata[0]} {trimac_fifo_block/rx_axis_mac_tdata[1]} {trimac_fifo_block/rx_axis_mac_tdata[2]} {trimac_fifo_block/rx_axis_mac_tdata[3]} {trimac_fifo_block/rx_axis_mac_tdata[4]} {trimac_fifo_block/rx_axis_mac_tdata[5]} {trimac_fifo_block/rx_axis_mac_tdata[6]} {trimac_fifo_block/rx_axis_mac_tdata[7]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list trimac_fifo_block/tri_mode_ethernet_mac_i/inst/tri_mode_ethernet_mac_support_clocking_i/gtx_clk_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 8 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {trimac_fifo_block/tx_axis_mac_tdata[0]} {trimac_fifo_block/tx_axis_mac_tdata[1]} {trimac_fifo_block/tx_axis_mac_tdata[2]} {trimac_fifo_block/tx_axis_mac_tdata[3]} {trimac_fifo_block/tx_axis_mac_tdata[4]} {trimac_fifo_block/tx_axis_mac_tdata[5]} {trimac_fifo_block/tx_axis_mac_tdata[6]} {trimac_fifo_block/tx_axis_mac_tdata[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_2_gtx_clk_out]
